In [ ]:
print("hello")

hello


# **Basic Array Creation**

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [ ]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# **Array Generation Function**

In [ ]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [ ]:
arr = np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
arr = np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [ ]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
arr = np.linspace(1,5,3)
arr

array([1., 3., 5.])

In [ ]:
arr = np.linspace(0,1,10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
arr = np.linspace(0,10,100)
arr

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

# **Random Number Generation**

In [ ]:
np.random.rand(5)

array([0.6052239 , 0.48868269, 0.98384034, 0.63658882, 0.8423864 ])

In [ ]:
np.random.randn(5)

array([ 0.13481949, -1.18628122, -0.92736058,  1.42830318, -1.08299313])

In [ ]:
np.random.randint(10,20,10)

array([19, 16, 17, 17, 18, 16, 10, 18, 17, 16])

# **Array Attributes**

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.shape

(3, 3)

In [ ]:
arr.size

9

In [ ]:
arr.dtype

dtype('int64')

# **Array Methods**

In [ ]:
arr.min()

np.int64(1)

In [ ]:
arr.max()

np.int64(9)

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.sum()

np.int64(45)

In [ ]:
np.sum(arr, axis = 0)

array([12, 15, 18])

In [ ]:
np.sum(arr, axis  = 1)

array([ 6, 15, 24])

In [ ]:
arr.mean()

np.float64(5.0)

In [ ]:
arr.std()

np.float64(2.581988897471611)

In [ ]:
arr.argmax()

np.int64(8)

In [ ]:
arr.argmin()

np.int64(0)

# **Reshaping and resizing**

In [ ]:
arr= np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

# **Numpy indexing and slicing of vectors**

In [ ]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[3]

np.int64(14)

In [ ]:
arr[1:5]

array([12, 13, 14, 15])

# **Numpy indexing and slicing of matrix**

In [ ]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr[2]

array([11, 12, 13, 14, 15])

In [ ]:
arr[2,3]

np.int64(14)

In [ ]:
arr[2:4, 1:3]

array([[12, 13],
       [17, 18]])

In [ ]:
arr[3:6, 3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [ ]:
arr[:,3]

array([ 4,  9, 14, 19, 24, 29])

# **Boolean Indexing**

In [ ]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [ ]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

# **Array Opeartions**

# **Arithmetic Operations**

In [ ]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a1 + a2

array([ 7,  9, 11, 13, 15])

In [ ]:
a2-a1

array([5, 5, 5, 5, 5])

In [ ]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [ ]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [ ]:
a2//a1

array([6, 3, 2, 2, 2])

In [ ]:
a2%a1

array([0, 1, 2, 1, 0])

In [ ]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

# **Broadcasting**

In [ ]:
l = [10,20,30,40]
arr = np.array(l)

In [ ]:
arr+10


array([20, 30, 40, 50])

# **Deep and shallow copy**

In [ ]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
slice_array = a[:5]
slice_array = slice_array * 10
slice_array

array([10, 20, 30, 40, 50])

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
b = a
b[0] = 69
b

array([69,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
a

array([69,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
c = a.copy()
c

array([69,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
c[0] = 99
c

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
a

array([69,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

# **Matrix Operation**

In [ ]:
A = np.array([[1,2], [3,4]])
B = np.array([[5, 6], [7,8]])

In [ ]:
A

array([[1, 2],
       [3, 4]])

In [ ]:
B

array([[5, 6],
       [7, 8]])

In [ ]:
A @ B

array([[19, 22],
       [43, 50]])

In [ ]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [ ]:
A.T

array([[1, 3],
       [2, 4]])

In [ ]:
B.T

array([[5, 7],
       [6, 8]])

# **Advance Array Manipulation**

# **Stacking Array**

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [ ]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.column_stack((a,b))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

# **Spliting array**

In [ ]:
c = np.arange(1,17).reshape(4,4)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
np.hsplit(c,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [ ]:
np.vsplit(c,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [ ]:
a = np.hsplit(c,4)
a

[array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]]),
 array([[ 4],
        [ 8],
        [12],
        [16]])]

In [ ]:
b = np.vsplit(c,4)
b

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]

In [ ]:
for i in a:
  print(i)

[[ 1]
 [ 5]
 [ 9]
 [13]]
[[ 2]
 [ 6]
 [10]
 [14]]
[[ 3]
 [ 7]
 [11]
 [15]]
[[ 4]
 [ 8]
 [12]
 [16]]


In [ ]:
for i in b:
  print(i)

[[1 2 3 4]]
[[5 6 7 8]]
[[ 9 10 11 12]]
[[13 14 15 16]]


# **Numpy Exercise**

In [ ]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [ ]:
#Get the shape of the matrix.

shape = np.shape(data)


In [ ]:
#Find the average age of students

avg_age = np.mean(data[:, 0])
avg_age


np.float64(18.4)

In [ ]:
#Extract Math marks of all students.

maths_marks = data[:, 1]
maths_marks

array([85, 92, 76, 65, 90])

In [ ]:
#Find the highest Science mark.

science_marks = data[:, 2]
np.max(science_marks)

np.int64(95)

In [ ]:
#Get details of the student who scored more than 90 in Math.

data[maths_marks > 90]

array([[19, 92, 88]])

In [ ]:
inc = maths_marks + 5
inc

array([90, 97, 81, 70, 95])

In [ ]:
#Find how many students are younger than 19.

age = data[:,0]
count = 0
for i in age:
  if i<19:
    count+=1
print(count)

3


In [ ]:
maths_avg = np.mean(maths_marks)
maths_avg

np.float64(81.6)

In [ ]:
science_avg = np.mean(data[:,2])
science_avg

np.float64(83.2)

In [ ]:
#Get data of students who scored at least 80 in both subjects.

data[(maths_marks >= 80) & (science_marks >= 80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [ ]:
#Replace all Science marks < 75 with 0.

data[science_marks < 75,2] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])

In [ ]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [ ]:
b = np.sum(s, axis = 0)
for i in b:
  if i != 45:
    print("Sudoku is not valid")
    break
else:
    print("For column it is valid now")

For column it is valid now


In [ ]:
c = np.sum(s, axis = 1)
for i in c:
  if i != 45:
    print("Sudoku is not valid")
    break
else:
    print("For row it is valid now")

For row it is valid now


In [ ]:
c = np.sum(s, axis = 1)
c

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [ ]:
b

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [ ]:
for i in range(0,9,3):
  for j in range(0,9,3):
    n= s[i:i+3, j:j+3]
    print(n.sum())

45
45
45
45
45
45
45
45
45
